name: pesummary
channels:
  - conda-forge
dependencies:
  - python 3.11
  # build
  - pip
  - setuptools>=61.0
  - setuptools-scm>=3.4.3
  # docs
  - pandoc
  # pin to sphinx<5 here to avoid pip issues with dependency resolution
  # (sphinx<5 is needed by sphinx-panels)
  - sphinx<5
